nome = input("Nome: ")
cpf = input("CPF: ")
idade = int(input("Idade: "))
print("-----------------------------")
print("Confirmação de cadastro:")
print ("Nome: ", nome)
print ("CPF: ", cpf)
print ("Idade: ", idade)
print("-----------------------------")